services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gopick-up
    ports:
      - "3000:3000"
    restart: always
    # environment:
    #   - DATABASE_URL=mongodb://mongo:27017/gopickup
